#Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]      # The name of the module we are configuring is "character"
#success_symbol = "[→](bold green) "
#error_symbol = "[←](bold red) "
#symbol = "➟"     # The "symbol" segment is being set to "➜"
#error_symbol = "✗"
#style_success = "bold #00A652"
#style_failure = "bold #df382c"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[git_branch]
#style = "bold blue"
truncation_length = 50
truncation_symbol = "..."

[git_status]

[custom.uname]
command = "uname -m"
format = "[$output]($style)"
shell = ["zsh"]
